# Generated by Django 6.0.6 on 2026-09-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('face_recall', 'Face Recall'), ('flip_card', 'Flip Card'), ('sound_match', 'Sound Match'), ('daily_routine', 'Daily Routine')], max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('stars', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='patients.patient')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
