# Generated by Django 6.0.6 on 2026-09-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('medicine', 'Medicine'), ('hydration', 'Hydration'), ('appointment', 'Appointment'), ('activity', 'Activity')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('scheduled_time', models.TimeField()),
                ('voice_clip_url', models.URLField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=True)),
                ('days_of_week', models.CharField(default='mon,tue,wed,thu,fri,sat,sun', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
